name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          # Configure git credential store
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
          # Remove any existing gitops directory
          rm -rf gitops
          
          # Clone repository using HTTPS URL without token
          git clone https://github.com/rslim087a/grade-api-gitops.git gitops
          cd gitops

          cat deployment.yaml
          
          # ---------- GITOPS UPDATE: Windows (Git Bash) ----------
          - name: Update image in GitOps repo (Windows Git Bash)
            if: runner.os == 'Windows'
            shell: "C:\\Program Files\\Git\\usr\\bin\\bash.exe -eo pipefail {0}"
            env:
              GIT_TOKEN: ${{ secrets.GIT_TOKEN }}   # PAT with repo write on rslim087a/grade-api-gitops
              NEW_SHA: ${{ github.sha }}
              IMAGE: ${{ env.IMAGE }}
            run: |
              set -euxo pipefail
    
              rm -rf gitops
              git clone https://github.com/rslim087a/grade-api-gitops.git gitops
              cd gitops
    
              # GNU sed in Git Bash supports -i without backup suffix
              sed -i "s|image: ${IMAGE}:.*|image: ${IMAGE}:${NEW_SHA}|g" deployment.yaml
              cat deployment.yaml
                    
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          
          # Push
          git push -f https://${GIT_TOKEN}@github.com/rslim087a/grade-api-gitops.git main
