name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

env:
  IMAGE: ghcr.io/ssamyrepo/kubernetes-cicd-tutorial
  GITOPS_REPO: rslim087b/grade-api-gitops   # <-- choose the right one
  GITOPS_FILE: deployment.yaml

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}

      - name: Update GitOps repo (Windows PowerShell)
        if: runner.os == 'Windows' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        shell: "powershell -NoProfile -ExecutionPolicy Bypass -Command \"& {0}\""  
        env:
          IMAGE: ghcr.io/ssamyrepo/kubernetes-cicd-tutorial
          GITOPS_REPO: rslim087b/grade-api-gitops                 # <-- confirm
          GITOPS_FILE: deployment.yaml
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}                    # PAT with write to that repo
          NEW_SHA: ${{ github.sha }}
        run: |
          $ErrorActionPreference = 'Stop'
      
          if ([string]::IsNullOrWhiteSpace($env:GIT_TOKEN)) { throw "GIT_TOKEN is empty." }
          if ([string]::IsNullOrWhiteSpace($env:IMAGE)) { throw "IMAGE is empty." }
      
          if (Test-Path gitops) { Remove-Item -Recurse -Force gitops }
      
          # Clone WITH token to avoid auth issues on private repos
          git clone "https://$($env:GIT_TOKEN)@github.com/$($env:GITOPS_REPO).git" gitops
          Set-Location gitops
      
          # Avoid CRLF churn on Windows runners
          git config core.autocrlf false
      
          $path = $env:GITOPS_FILE
          if (!(Test-Path $path)) { throw "File not found: $path" }
      
          $content = Get-Content -Raw -Path $path
          $pattern = '^\s*image:\s*.*$'
          $replacement = "image: $($env:IMAGE):$($env:NEW_SHA)"
          $new = [regex]::Replace($content, $pattern, $replacement, 'Multiline')
      
          if ($new -ne $content) {
            Set-Content -Path $path -Value $new -Encoding UTF8
      
            git config user.name  "GitHub Actions"
            git config user.email "actions@github.com"
            git add $path
            git commit -m "Update image to $env:NEW_SHA"
      
            # Push WITH token explicitly
            git push "https://$($env:GIT_TOKEN)@github.com/$($env:GITOPS_REPO).git" HEAD:main
      
            # Optional: scrub token from local .git/config then delete working dir
            git remote set-url origin "https://github.com/$env:GITOPS_REPO.git"
          } else {
            Write-Host "No changes to commit."
          }
      
          # Cleanup workspace (avoid leaving PAT in .git/config)
          Set-Location ..
          Remove-Item -Recurse -Force gitops
