name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

env:
  IMAGE: ghcr.io/ssamyrepo/kubernetes-cicd-tutorial
  GITOPS_REPO: rslim087b/grade-api-gitops   # <-- choose the right one
  GITOPS_FILE: deployment.yaml

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}

      # -------- GitOps update (Linux/macOS) --------
      - name: Update GitOps repo (bash)
        if: runner.os != 'Windows' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }} # PAT with write on the GitOps repo
          NEW_SHA: ${{ github.sha }}
        run: |
          set -euxo pipefail
          rm -rf gitops
          git clone "https://github.com/${GITOPS_REPO}.git" gitops
          cd gitops

          # Update the image tag line (handles indentation)
          sed -i "s|^\s*image:\s*.*$|image: ${IMAGE}:${NEW_SHA}|g" "${GITOPS_FILE}"

          git config user.name  "GitHub Actions"
          git config user.email "actions@github.com"
          git add "${GITOPS_FILE}"

          if ! git diff --cached --quiet; then
            git commit -m "Update image to ${NEW_SHA}"
            git push "https://${GIT_TOKEN}@github.com/${GITOPS_REPO}.git" HEAD:main
          else
            echo "No changes to commit."
          fi

      # -------- GitOps update (Windows) --------
      - name: Update GitOps repo (Windows PowerShell)
        if: runner.os == 'Windows' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        shell: powershell
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
          NEW_SHA: ${{ github.sha }}
        run: |
          $ErrorActionPreference = 'Stop'

          if ([string]::IsNullOrWhiteSpace($env:GIT_TOKEN)) { throw "GIT_TOKEN is empty." }
          if ([string]::IsNullOrWhiteSpace($env:IMAGE)) { throw "IMAGE is empty." }

          if (Test-Path gitops) { Remove-Item -Recurse -Force gitops }
          git clone "https://github.com/$env:GITOPS_REPO.git" gitops
          Set-Location gitops

          $path = $env:GITOPS_FILE
          if (!(Test-Path $path)) { throw "File not found: $path" }

          $content = Get-Content -Raw -Path $path
          $pattern = '^\s*image:\s*.*$'
          $replacement = "image: $($env:IMAGE):$($env:NEW_SHA)"
          $new = [regex]::Replace($content, $pattern, $replacement, 'Multiline')

          if ($new -ne $content) {
            Set-Content -Path $path -Value $new -Encoding UTF8
            git config user.name  "GitHub Actions"
            git config user.email "actions@github.com"
            git add $path
            git commit -m "Update image to $env:NEW_SHA"
            git push "https://$($env:GIT_TOKEN)@github.com/$($env:GITOPS_REPO).git" HEAD:main
          } else {
            Write-Host "No changes to commit."
          }
